### ISSUE TITLE
`AttributeError` when importing `qutip_jax` with M2 chip

### ISSUE THREAD

**Issue by ofw24** [qutip/qutip-jax#61]
When importing `qutip_jax`, I'm seeing an `AttributeError` within `qutip.core.data` when referencing `sqrtm` within `qutip-jax/src/qutip-jax/unary`. Looking through the source code it seems like the implementation lies within `qutip/core/data/expm`, but this isn't referenced correctly and causes the ImportError.

To recreate:
`import qutip-jax`

Output:
`AttributeError: module 'qutip.core.data' has no attribute 'sqrtm'`

**Comment by Ericgig** [comment]
To use the development version of `qutip-jax`, you will need the development version of qutip. 
If you install qutip from source, it should work. 
The branch `dev.major` have a few extra addition to support `jit` and `grad` with some functions. 
See https://qutip-jax.readthedocs.io/en/latest/metrics.html

**Comment by ofw24** [comment]
Great, this seems to have fixed the issue. Thanks!
